class Autogenerated {
  List<Data> ?data;

  Autogenerated({this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      // ignore: deprecated_member_use
      data =  <Data>[];
      json['data'].forEach((v) {
        data?.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data?.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String ?id;
  String ?seriesName;
  String ?created;
  String ?team1;
  Null team1ProfileImage;
  String ?team2;
  Null team2ProfileImage;
  String ?rating;
  String ?popularity;
  int ?price;

  Data(
      {this.id,
      this.seriesName,
      this.created,
      this.team1,
      this.team1ProfileImage,
      this.team2,
      this.team2ProfileImage,
      this.rating,
      this.popularity,
      this.price});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    seriesName = json['series_name'];
    created = json['created'];
    team1 = json['team1'];
    team1ProfileImage = json['team1_profile_image'];
    team2 = json['team2'];
    team2ProfileImage = json['team2_profile_image'];
    rating = json['rating'];
    popularity = json['popularity'];
    price = json['price'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['series_name'] = this.seriesName;
    data['created'] = this.created;
    data['team1'] = this.team1;
    data['team1_profile_image'] = this.team1ProfileImage;
    data['team2'] = this.team2;
    data['team2_profile_image'] = this.team2ProfileImage;
    data['rating'] = this.rating;
    data['popularity'] = this.popularity;
    data['price'] = this.price;
    return data;
  }
}